#pragma once

#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416

#define MAP_WIDTH 16
#define MAP_HEIGHT 13

#define TILE_WIDTH 32
#define TILE_HEIGHT 32;

#define FALL_SPEED 2
#define INITIAL_JUMP_FORCE 400.0f
#define JUMP_FORCE_DECREMENT 400.0f
#define GRAVITY_STRENGTH 110.0f

#define SCREENSHAKE_DURATION 0.25f

#define INJURED_TIME 2.5f

#define KOOPA_SPEED 96.0f

